/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlinputRouteImport } from './routes/urlinput'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as IndexRouteImport } from './routes/index'

const UrlinputRoute = UrlinputRouteImport.update({
  id: '/urlinput',
  path: '/urlinput',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/urlinput': typeof UrlinputRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/urlinput': typeof UrlinputRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/urlinput': typeof UrlinputRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/details'
    | '/login'
    | '/register'
    | '/results'
    | '/urlinput'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/details' | '/login' | '/register' | '/results' | '/urlinput'
  id:
    | '__root__'
    | '/'
    | '/details'
    | '/login'
    | '/register'
    | '/results'
    | '/urlinput'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailsRoute: typeof DetailsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResultsRoute: typeof ResultsRoute
  UrlinputRoute: typeof UrlinputRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urlinput': {
      id: '/urlinput'
      path: '/urlinput'
      fullPath: '/urlinput'
      preLoaderRoute: typeof UrlinputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailsRoute: DetailsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResultsRoute: ResultsRoute,
  UrlinputRoute: UrlinputRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
